### ISSUE TITLE
New release since API change

### ISSUE THREAD

**Issue by hugecannon** [cstockton/go-conv#5]
Since https://github.com/cstockton/go-conv/commit/4f55da38d4891bcfa16ad3407cd5f1fafad40372 introduces a significant change to the API, would it be worth making a v2 release?

**Comment by cstockton** [comment]
Hi there, since it was a BC break if you are using the OLD version and need to continue to use it for a while I set up this import for you: gopkg.in/cstockton/go-conv.v1 - The current version of the API will not change so it's okay to use master moving forward. I'm not opposed to tagging master as  gopkg.in/cstockton/go-conv.v2 if you would like me to though.

**Comment by hugecannon** [comment]
Ah, great, all good then :+1:
